version: "3.5"
services:
   pegasus-annex:
      image: pegasus/pegasus-annex:latest
      container_name: pegasus-annex
      hostname: pegasus-annex
#      network_mode: host
      restart: always
      volumes:
         - ./data/test:/home/pegasus/test:rw
