version: "3.5"
services:
   pegasus-annex:
      image: pegasus/pegasus-annex:latest
      container_name: pegasus-annex
      hostname: pegasus-annex
#      network_mode: host
      restart: always
      volumes:
         - ./data/test:/home/pegasus/test:rw
      # the collector running inside the container listens on port 9618
      ports:
         - "9618:9618"
      environment:
         - HOST_IP
